### ISSUE TITLE
Able to execute commands in the VPS.

### ISSUE THREAD

**Issue by Kabir-Sidhu** [YajTPG/pterodactyl-eggs#13]
So, one of my staff members discovered an "issue" with the eggs. You can set one of the startup parameters to `bash` and execute commands in the container that your server is in.

**Comment by YajTPG** [comment]
You can change `required|string|max:256` to `required|string|max:256|not_in:bash` in your egg settings, this will prevent them from entering the value `bash` as the startup commands.
You should also add `sh`.

**Comment by Kabir-Sidhu** [comment]
uwu awigatou

**Comment by BasToTheMax** [comment]
And. What could you do with bash? The container user doesn't have root permissions.
