### ISSUE TITLE
Php egg not working i put 2nd Start up php index.php

### ISSUE THREAD

**Issue by Pekly** [YajTPG/pterodactyl-eggs#19]
Not working

**Comment by YajTPG** [comment]
Can you explain a bit more? Maybe an error message or wings logs?

**Comment by YajTPG** [comment]
Feel free to reopen this issue when you have more info.

**Comment by Pekly** [comment]
Like using wordpress it gives me error see the screenshot

**Comment by YajTPG** [comment]
There is no screenshot, seems like GitHub didn't pick up the screenshot you probably attached with your email reply
