### ISSUE TITLE
PHP egg not working

### ISSUE THREAD

**Issue by Krish-Panchani** [YajTPG/pterodactyl-eggs#20]
I think this is happening because of docker entrypoint script is empty.

**see console errors**
```
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from yajtpg/pterodactyl-images 
Status: Image is up to date for quay.io/yajtpg/pterodactyl-images:php-8.1 
Digest: sha256:74af096f4a28bb6a5d9ff498ee847c219c351f5b1f936a124c711a2b324daab2 
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /usr/local/bi
![Screenshot (755)](https://user-images.githubusercontent.com/74005086/183575557-c9d173fc-b17c-42a9-a578-4aafd031ee42.png)
n/docker-php-entrypoint: exec format error
container@pterodactyl~ Server marked as running...
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. 
```

**Comment by YajTPG** [comment]
Usually `exec format error` happens because the binary (docker image in this case) is built for another architecture than the one you're using.
Is your server using arm64 processor by any chance? If possible, can you run `uname -a` on the host machine and paste the output here?

**Comment by Krish-Panchani** [comment]
> Usually `exec format error` happens because the binary (docker image in this case) is built for another architecture than the one you're using.
> Is your server using arm64 processor by any chance? If possible, can you run `uname -a` on the host machine and paste the output here?

`#17~20.04.1-Ubuntu SMP Mon Jul 4 05:29:46 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by YajTPG** [comment]
Seems like you're using a `arm64 (aarch64)` processor which isn't supported by my docker images, not sure either if I'll be adding support for them.
