### ISSUE TITLE
[Egg request] Azuracast

### ISSUE THREAD

**Issue by pascalwiersma** [YajTPG/pterodactyl-eggs#25]
hey! I don't know if it's possible, but it would be great if this were possible in pterodactyl, namely Azuracast.

This is it:
https://github.com/AzuraCast/AzuraCast

Let me know if it is possible :).

Greetings,
Pascal

**Comment by YajTPG** [comment]
Heya,

Had a look at their installation docs, this is not possible since it requires docker-compose to run and is not designed to run on pterodactyl.
