### ISSUE TITLE
nodejs 18 docker image

### ISSUE THREAD

**Issue by Pete9xi** [YajTPG/pterodactyl-eggs#28]
I have cmake installed on the host my nodejs application needs to build binding files via cmake how do i add cmkae to the docker image? FYI i have no experience with docker.

**Comment by Pete9xi** [comment]
also tired using your image as a base but it fails to instal cmake 
# Use the existing image as the base image
FROM quay.io/yajtpg/pterodactyl-images:nodejs-18

RUN apt-get update && apt-get install -y cmake


also tried RUN apk add cmake

**Comment by YajTPG** [comment]
Heyo, cmake is already in installed the docker image, if you want to add additional modules, can do so by using the image as base and switching the user to root to be able to install them.

Here's an example:
```Dockerfile
FROM quay.io/yajtpg/pterodactyl-images:nodejs-18

USER root

RUN apt-get update && apt-get install -y cmake && apt clean
# Don't forget to switch back to the original user :)
USER container
```
