### ISSUE TITLE
Rewamp Devil's "fork-rewrite"

### ISSUE THREAD

**Issue by FoksVHox** [YajTPG/pterodactyl-eggs#3]
Take some time to ensure all of these are working, and maybe adding them to the repo? 
https://gitlab.com/devil38/fork-rewrite/-/branches/all

**Comment by YajTPG** [comment]
Tbh Devil was the guy who I got inspired by to make these eggs. If you do look at his Merge Requests, he hasn't accepted any. I doubt he would but will give it a try after my exams.

**Comment by FoksVHox** [comment]
Well, I was thinking about including all of them, in this repo.

**Comment by YajTPG** [comment]
Feel free to do that, I don't really provide dockerfiles as of now and all of his images are open source

**Comment by YajTPG** [comment]
It's kinda easy to reverse a docker image to get the dockerfile tho

**Comment by YajTPG** [comment]
No idea what happened to the gitlab repo, closing this issue
