### ISSUE TITLE
This file cannot be modified: present in egg denylist. in Python egg when uploading a JSON file.

### ISSUE THREAD

**Issue by Kabir-Sidhu** [YajTPG/pterodactyl-eggs#4]
So, I was tryna upload a JSON file named `shit.json`. It was the config file for my bot, but it gave me this error `This file cannot be modified: present in egg denylist.`. When I tried to rename and then upload, it gave me the same error. I even tried creating the file through the file manager, then it raised this error `[Wings Error]: This file cannot be modified: present in egg denylist.`.

**Comment by YajTPG** [comment]
Hmm, I'll look into this in a few hours.

**Comment by YajTPG** [comment]
I can import the file perfectly, would you mind supplying me the logs?

**Comment by Kabir-Sidhu** [comment]
@YajTPG Sorry for the delay with replying, here are the logs: https://ptero.co/dapuwejabo

**Comment by YajTPG** [comment]
Hmm, I don't really see anything related to the eggs, panel logs please?

**Comment by Kabir-Sidhu** [comment]
> Hmm, I don't really see anything related to the eggs, panel logs please?

http://bin.ptdl.co/ti2um here you go

**Comment by Kabir-Sidhu** [comment]
The issue was not with the eggs.

**Comment by YajTPG** [comment]
👍
