### ISSUE TITLE
Mongodb

### ISSUE THREAD

**Issue by NoodlesDev987** [YajTPG/pterodactyl-eggs#6]
Create mongodb egg

**Comment by NoodlesDev987** [comment]
Also please create egg for mongodb gui - https://github.com/nosqlclient/nosqlclient

**Comment by YajTPG** [comment]
Thank you for the suggestion, will look into this.

**Comment by NoodlesDev987** [comment]
Also please create egg for this mongodb gui https://github.com/nosqlclient/nosqlclient

**Comment by YajTPG** [comment]
I'll likely not be adding something other than plain coding languages for now, closing this.
