### ISSUE TITLE
Custom domains

### ISSUE THREAD

**Issue by NoodlesDev987** [YajTPG/pterodactyl-eggs#7]
How can i connect custom domain to container?

**Comment by YajTPG** [comment]
You'll need to add an A record that points to the machine's IP address. Then you should be able to use it like (Domain):(PORT)

**Comment by NoodlesDev987** [comment]
Ok, ik that I need to point A record to vps IP, but I want to able to use custom domain without port

**Comment by YajTPG** [comment]
Hmm, I don't think that's possible.

**Comment by ririko5834** [comment]
It is, some hosts have their proxy server to setup own domain

**Comment by YajTPG** [comment]
I'm pretty sure you'll need to do a lot of internal configuration which port-forwards the container p[ort to port 80 and 443.

**Comment by BasToTheMax** [comment]
If you are the owner of the vps, you can install NGINXProxyManager on it to manage custom domains. Otherwise, it is not possible

**Comment by Bossa9973** [comment]
Use cloudflare tunnel
