### ISSUE TITLE
Php egg is not working

### ISSUE THREAD

**Issue by ririko5834** [YajTPG/pterodactyl-eggs#8]
I created file index.php in pterodactyl container where is your universal php egg and its not working:

![image](https://user-images.githubusercontent.com/64729293/113476280-d70ff400-947a-11eb-953e-79e6ae797a9e.png)

**Comment by YajTPG** [comment]
Sorry for the late response, would you mind telling me what your first and second startup commands are?

**Comment by NoodlesDev987** [comment]
First was `echo hi` and the second was empty

**Comment by ririko5834** [comment]
My configuration: 
![image](https://user-images.githubusercontent.com/64729293/113557984-2aab4a80-95ff-11eb-8429-6a34b8c419ae.png)

Files:
![image](https://user-images.githubusercontent.com/64729293/113558009-35fe7600-95ff-11eb-9735-714198d647d3.png)

**Comment by YajTPG** [comment]
Change your 2nd startup command to `php index.php`, that should work

**Comment by ririko5834** [comment]
Then when I have more php files, will it work for all of them?

For example I want to host https://osticket.com

**Comment by YajTPG** [comment]
It should.
Usually if you want to host a entire website based on PHP, you'll probably need to use a Nginx egg which has PHP-fpm included.

**Comment by ririko5834** [comment]
Can you make nginx egg with multi php versions support?

**Comment by YajTPG** [comment]
I'll likely not be adding something other than plain coding languages for now, closing this.
